export const CandidateActionTypes = {
    FETCH_API_START: 'FETCH_API_START',
    FETCH_API_SUCCESS: 'FETCH_API_SUCCESS',
    FETCH_API_FAILURE: 'FETCH_API_FAILURE',
    ADD_SEARCH_FIELD: 'ADD_SEARCH_FIELD',
    SHORTLISTED: 'SHORTLISTED',
    REJECTED: 'REJECTED'
}